development: &default
  adapter: postgresql
  database: hesap_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: root
  password: 1234

test:
  <<: *default
  database: hesap_test